// apps/web/features/inspiration/components/ImageSelector.tsx
"use client";

import { cn } from "@/shared/lib/utils";

export function ImageSelector({
  images,
  selected,
  onSelect,
}: {
  images: string[];
  selected: number | null;
  onSelect: (index: number) => void;
}) {
  return (
    <div>
      <h3 className="mb-2 text-sm font-medium">Imágenes generadas</h3>
      <div className="grid grid-cols-5 gap-3" data-testid="image-grid">
        {images.map((url, i) => (
          <button
            type="button"
            key={url}
            data-testid={`image-option-${i}`}
            aria-pressed={selected === i}
            onClick={() => onSelect(i)}
            className={cn(
              "aspect-square overflow-hidden rounded border-2",
              selected === i ? "border-blue-600" : "border-transparent",
            )}
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={url} alt={`Opción ${i + 1}`} className="h-full w-full object-cover" />
          </button>
        ))}
      </div>
    </div>
  );
}

// apps/web-angular/src/app/features/inspiration/ui/image-selector.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';

/** Presentational grid of generated images; emits the chosen index upward. */
@Component({
  selector: 'app-image-selector',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 class="mb-2 text-sm font-medium">Imágenes generadas</h3>
    <div class="grid grid-cols-5 gap-3">
      @for (url of images(); track url; let i = $index) {
        <button
          type="button"
          class="aspect-square overflow-hidden rounded border-2"
          [class.border-blue-600]="selectedIndex() === i"
          [class.border-transparent]="selectedIndex() !== i"
          [attr.aria-pressed]="selectedIndex() === i"
          (click)="select.emit(i)"
        >
          <img [src]="url" [alt]="'Opción ' + (i + 1)" class="h-full w-full object-cover" />
        </button>
      }
    </div>
  `,
})
export class ImageSelector {
  readonly images = input.required<string[]>();
  readonly selectedIndex = input<number | null>(null);
  readonly select = output<number>();
}
