// apps/web-angular/src/app/features/campaigns/ui/ad-preview.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import { Ad } from '../../../shared/models/api.models';

/** Facebook-style preview of a persisted ad. Pure presentational. */
@Component({
  selector: 'app-ad-preview',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="max-w-sm rounded-lg border border-gray-200">
      <img [src]="ad().image_url" [alt]="ad().headline" class="aspect-square w-full rounded-t-lg object-cover" />
      <div class="p-3">
        <div class="font-semibold">{{ ad().headline }}</div>
        <p class="text-sm text-gray-600">{{ ad().body }}</p>
        <button class="mt-2 rounded bg-blue-600 px-3 py-1 text-xs font-medium text-white">
          {{ ad().cta.replace('_', ' ') }}
        </button>
      </div>
    </div>
  `,
})
export class AdPreview {
  readonly ad = input.required<Ad>();
}

// apps/web/features/campaigns/components/AdPreview.tsx
"use client";

import type { Ad } from "../types";

export function AdPreview({ ad }: { ad: Ad }) {
  return (
    <div data-testid="ad-card-preview" className="max-w-sm rounded-lg border border-gray-200">
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={ad.image_url} alt={ad.headline} className="aspect-square w-full rounded-t-lg object-cover" />
      <div className="p-3">
        <div className="font-semibold">{ad.headline}</div>
        <p className="text-sm text-gray-600">{ad.body}</p>
        <button className="mt-2 rounded bg-blue-600 px-3 py-1 text-xs font-medium text-white">
          {ad.cta.replace("_", " ")}
        </button>
      </div>
    </div>
  );
}
